### PR TITLE
Add OPTION_AUTH (option 11)

### PR DESCRIPTION
**Pull request by thperret**
My ISP request the AUTH option to get a DHCPv6 lease.
This would close openwrt/odhcp6c#48 (even if the issue name is misleading, but I opened it only for this option to be included)

### CODE REVIEW

**Comment by themiron** [comment]
hi, the way 11 option (OPTION_AUTH) is used here is incorrect. it's not static, but consists of different fields, included/modified/excluded in runtime.
refer rfc3315 section 22.11 and 21

**Comment by thperret** [comment]
hum, indeed!
Sorry I didn't take the time to read it. I could try to implement it correctly although I wouldn't be able to test it and it would break the compatibility with my ISP. Yes, my ISP requires some non-standard options to be send (being this static custom OPTION_AUTH).
Would it be conceivable to implement this custom and not standard option (obviously not with the official name OPTION_AUTH)?
Anyway, you can close this PR for now.
Thanks

**Comment by themiron** [comment]
hi, is it possible to know, what shoudl be the value of 11th options for your ISP?
it might be something per standard, just curious

**Comment by thperret** [comment]
the value in hex is:
```
00:00:00:00:00:00:00:00:00:00:00:66:74:69:2f:*:*:*:*:*:*:*
```
the last `*` being the login infos provided by the ISP (an alphanumeric string of 6 characters)
The ISP also requires to override the USERCLASS and VENDORCLASS options.

**Comment by themiron** [comment]
thanks, your auth option seems rfc-formatted, so it might be worth to all more general support
`protocol:	0x00`
`algorithm:	0x00`
`RDM:	0x00`
`replay detection:	00:00:00:00:00:00:00:00`
`auth-info:	66:74:69:2f:*:*:*:*:*:*:*`

**Comment by thperret** [comment]
ok, I (try to) read the RFC and I realized that the OPTION_AUTH (I think?) seems [already correctly implemented](https://github.com/openwrt/odhcp6c/blob/master/src/dhcpv6.c#L704).
So I just added an option to specify a static AUTH which is clearly not standard and I don't see how I could modify the correct implementation to satisfy my needs (predictive authentication informations)
Another option would be to implement the same mechanism used by udhcpc in busybox: using a command line option to specify options to send (I'm already using that for DHCPv4 lease for which my ISP requires also a non standard authentication option 90). In that case I could override the standard and just send the packet I need?

**Comment by kgersen** [comment]
Hi, we're trying to do the same thing too (discussions about this in French here: https://lafibre.info/remplacer-livebox/sosh-fibre-openwrt-avec-ip-fixe-et-ipv6/msg391802/#msg391802 )

Indeed our ISP (Orange) expects a RFC formatted option 11 but not RFC compliant values (everything is at 0 except the auth-info).

So in term of implementation is way better to add a way to send custom options instead of messing with the existing option 11. 
The PR proposed by tperret in #48 seems to do the job.
What is then missing from it is exposing that extra option in UCI. (same syntax as IPv4 so 'sendopts').

**Pull request closed without merging**
